# docker-compose.yml
version: '3.8'

services:
  web:
    image: seanstilwell/hello-world-dash:latest
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "8080:8080"